//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DjVu Sep.rc
//
#define IDS_ABOUTBOX                    101
#define IDD_DJVUSEP_DIALOG              102
#define STRING_SK_BACKGROUND_FILES      102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_NEW_FOLDER           132
#define IDD_DIALOG_OPTIONS              134
#define IDD_DIALOG_PROGRESS             136
#define IDC_BUTTON_OPEN_FILES           1000
#define IDC_BUTTON_CONVERT              1001
#define IDC_STATIC_OUT_SUFFIX           1001
#define IDC_BUTTON_ADD                  1002
#define IDC_STATIC_OTHER_OPTIONS        1002
#define IDC_STATIC_MAIN_OPTIONS         1002
#define IDC_BUTTON_INSERT_DJVU          1003
#define IDC_STATIC_FILE_ADDON           1003
#define IDC_BUTTON_OPTIONS              1004
#define IDC_STATIC_FILE_ADDON2          1004
#define IDC_BUTTON_HELP                 1005
#define IDC_BUTTON_OPEN_FOLDER          1006
#define IDC_BUTTON_REMOVE               1007
#define IDC_COMBO_ENC_PROFILE           1008
#define IDC_BUTTON_RESET                1009
#define IDC_RADIO_COMMA                 1010
#define IDC_RADIO_PLUS                  1011
#define IDC_RADIO_ALL                   1012
#define IDC_CHECK_OUTPUT_DESKTOP        1012
#define IDC_RADIO_CURRENT               1013
#define IDC_CHECK_CUSTOM_FILENAME       1013
#define IDC_PREFIX                      1014
#define IDC_CHECK_RECOGNIZE_ST_FILENAMES 1014
#define IDC_STATIC_SIZE                 1015
#define IDC_SUFFIX                      1015
#define IDC_BUTTON_VIEW                 1016
#define IDC_NONE                        1016
#define IDC_BUTTON_CURRENT              1017
#define IDC_PREFIX2                     1017
#define IDC_STATIC_PARAMETERS           1018
#define IDC_SUFFIX2                     1018
#define IDC_CHECK_BSF                   1019
#define IDC_NONE2                       1019
#define IDC_CHECK_ENC_PROFILE           1020
#define IDC_STATIC_BACKGROUND           1020
#define IDC_STATIC_BACKGROUND2          1020
#define IDC_CHECK_BG                    1020
#define IDC_STATIC_APPLY_TO             1021
#define IDC_STATIC_FOREGROUND           1021
#define IDC_STATIC_FILE_ADDON22         1021
#define IDC_PREFIX22                    1022
#define IDC_CHECK_DPI                   1022
#define IDC_LIST_FILES                  1023
#define IDC_STATIC_SIGN1                1023
#define IDC_SUFFIX22                    1023
#define IDC_STATIC_SIGN2                1024
#define IDC_NONE22                      1024
#define IDC_SLIDER_BG                   1024
#define IDC_STATIC_SIGN3                1025
#define IDC_STATIC_LANGUAGE2            1025
#define IDC_STATIC_CHUNKS               1026
#define HELP_PATHNAME                   1026
#define IDC_STATIC_BG                   1026
#define IDC_COMBO_CTRL_PROFILE          1027
#define IDC_BUTTON_OUTPUT_DJVU          1028
#define IDC_STATIC_PROFILES             1028
#define IDC_EDIT_OUTPUT_DJVU            1029
#define IDC_COMBO_LANGUAGE              1029
#define IDC_BUTTON_SAVE_PROFILE         1030
#define IDC_EDIT_NEW_FOLDER             1031
#define IDC_BUTTON_DELETE_PROFILE       1031
#define IDC_BUTTON_INPUT_DJVU           1032
#define IDC_COMBO_DPI                   1032
#define IDC_STATIC_NOTATION             1033
#define IDC_EDIT_INPUT_DJVU             1033
#define IDC_STATIC_LANGUAGE             1034
#define IDC_STATIC_ENC_STATUS           1041
#define IDC_STATIC_ENC_PAGES            1042
#define IDC_PROGRESS_ENCODING           1044
#define IDC_BUTTON_ENC_CANCEL           1045
#define IDC_COMBO_BSF                   1060
#define IDC_EDIT_CH4                    1066
#define IDC_SPIN_CH4                    1067
#define IDC_EDIT_CH3                    1070
#define IDC_SPIN_CH3                    1071
#define IDC_EDIT_CH2                    1074
#define IDC_SPIN_CH2                    1075
#define IDC_EDIT_CH1                    1078
#define IDC_SPIN_CH1                    1079
#define IDC_EDIT_OUT_SUFFIX             1080
#define IDC_EDIT_FILE_ADDON             1081
#define IDC_EDIT_FILE_ADDON2            1082
#define IDC_CHECK_OPEN_CONVERTED        1128
#define IDC_CHECK_OPEN_INSERTED         1129
#define IDC_STATIC_INPUT                1130
#define IDC_STATIC_NEW_FOLDER_NAME      1138
#define STRING_CHOOSE_INPUT_FILES       1146
#define STRING_CHOOSE_OUTPUT_FOLDER     1147
#define STRING_CREATE_NEW_FOLDER        1148
#define STRING_OPEN_FOLDER              1149
#define STRING_NEW_FOLDER               1154
#define STRING_NEW_FOLDER_NAME          1155
#define IDC_STATIC_INPUT2               1156
#define IDC_BUTTON_OPEN_FILES2          1158
#define IDC_BUTTON_OPEN_FOLDER2         1159
#define IDC_STATIC_PARAMETERS2          1160
#define IDC_CHECK_BSF2                  1161
#define IDC_STATIC_APPLY_TO2            1163
#define IDC_RADIO_ALL2                  1164
#define IDC_RADIO_CURRENT2              1165
#define IDC_BUTTON_CONVERT2             1166
#define IDC_BUTTON_VIEW2                1167
#define IDC_BUTTON_CURRENT2             1168
#define IDC_BUTTON_INSERT_DJVU2         1169
#define IDC_BUTTON_OPTIONS2             1170
#define IDC_BUTTON_HELP2                1171
#define IDC_BUTTON_INPUT_DJVU2          1172
#define IDC_BUTTON_OUTPUT_DJVU2         1173
#define IDS_STRING_KB                   1174
#define IDD_DIALOG_OPTIONS2             1176
#define IDC_STATIC_MAIN_OPTIONS2        1182
#define IDC_CHECK_OPEN_CONVERTED2       1183
#define IDC_CHECK_OPEN_INSERTED2        1184
#define IDC_CHECK_OUTPUT_DESKTOP2       1185
#define IDC_STATIC_OUT_SUFFIX2          1186
#define IDC_CHECK_CUSTOM_FILENAME2      1187
#define IDC_STATIC_FOREGROUND2          1188
#define STRING_CANCEL                   1189
#define STRING_PROCESSED_PAGES          1190
#define STRING_OF                       1191
#define STRING_CONVERSION_FAILED        1192
#define STRING_CONVERSION_STOPPED       1193
#define STRING_CONVERSION_SUCCESS       1194
#define STRING_PROGRESS                 1195
#define STRING_PROGRESS_STATUS          1196
#define STRING_FORE_FILES               1197
#define STRING_BACK_FILES               1198
#define STRING_WRONG_DJVU               1199
#define STRING_WRONG_OUTDJVU            1200
#define STRING_WRONG_DJVUPICS           1201
#define STRING_WRONG_INSERT             1202
#define STRING_GOOD_INSERT              1203
#define STRING_NO_VIEWER                1204
#define STRING_PROCESSING_FAILED        1205
#define STRING_NO_INPUTDJVU             1206
#define STRING_BAD_FORE_ADDON           1213
#define STRING_EMPTY_BACK_ADDON         1214
#define STRING_BAD_BACK_ADDON           1215
#define STRING_EMPTY_FORE_ADDON         1216
#define IDC_CHECK_BG2                   1217
#define STRING_REMOVE_FILE              1218
#define STRING_FROM_LIST                1219
#define STRING_QFILES                   1220
#define STRING_TOO_COLORS               1221
#define STRING_ERROR_ON_FILE            1222
#define STRING_FIT_BITMAPS              1223
#define STRING_ONLY_24_8_BITMAPS        1224
#define STRING_RASTER_FILES             1225
#define STRING_FILES                    1226
#define STRING_LIST_COLUMN0             1227
#define STRING_LIST_COLUMN1             1228
#define STRING_NON_NUMERIC              1229
#define IDC_CHECK_RECOGNIZE_ST_FILENAMES2 1230
#define STRING_NOT_EQUAL1               1231
#define STRING_NOT_EQUAL2               1232
#define STRING_NOT_EQUAL3               1233
#define STRING_NOT_EQUAL4               1234
#define STRING_INSERTION                1235
#define STRING_INSERTION_STATUS         1236
#define STRING_INSERTION_STOPPED        1237
#define STRING_NOT_NUMBER1              1238
#define STRING_NOT_NUMBER2              1239
#define STRING_NOT_NUMBER3              1240
#define STRING_NOT_NUMBER4              1241

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
